base_url: "https://jsonplaceholder.typicode.com"

test_data:
  valid_resource_creation:
    title: "create valid resource"
    body: "create valid resource"
    userId: 1

  invalid_resource_with_missing_title_field:
    body: "create invalid resource"
    userId: 2

  invalid_resource_with_empty_body:
    title: "create invalid resource with empty body"
    body: ""
    userId: 3

  valid_resource_id: 1
  invalid_resource_id: 9999
